-- AlterTable
ALTER TABLE "Course" ALTER COLUMN "status" SET DEFAULT true,
ALTER COLUMN "accessPeriod" SET DATA TYPE TEXT,
ALTER COLUMN "liveClassTime" SET DATA TYPE TEXT,
ALTER COLUMN "price" SET DATA TYPE TEXT;
